@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTc2NDg5NDMxNiwiZXhwIjoxNzY0ODk0NjE2fQ.n7pcVg8xmjtVeVrdUV1tlsNoMN0HYCbw0f7Uhx2SHw8

### Gerar Token
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "senha": "admin"
}

### Criar usuario
POST http://localhost:3000/auth/usuarios HTTP/1.1
content-type: application/json
x-access-token: {{token}}

{
    "username": "Lino",
    "senha": "admin",
    "nome_completo": "Alysson Lino"
}

### Criar proprietario
POST http://localhost:3000/auth/proprietarios HTTP/1.1
content-type: application/json
x-access-token: {{token}}

{
    "cpf": "111",
    "nome": "Lino", 
    "fone": "55555"
}

### Criar veiculo
POST http://localhost:3000/auth/veiculos HTTP/1.1
content-type: application/json
x-access-token: {{token}}

{
    "placa_veiculo": "XYZ-9876",
    "id_modelo": 3,
    "id_proprietario": 3,
    "preco_veiculo": 85000.00,
    "ano": 2022
}

### Listar proprietarios
GET http://localhost:3000/auth/proprietarios HTTP/1.1
x-access-token: {{token}}

### Listar veiculos
GET http://localhost:3000/auth/veiculos HTTP/1.1
x-access-token: {{token}}

### Listar usuarios
GET http://localhost:3000/auth/usuarios HTTP/1.1
x-access-token: {{token}}

### Deletar usuario
DELETE http://localhost:3000/auth/usuarios/2 HTTP/1.1
x-access-token: {{token}}

{
    "id": 5
}
### Deletar proprietario
DELETE http://localhost:3000/auth/proprietarios/2 HTTP/1.1
x-access-token: {{token}}

{
    "id": 2
}
### Deletar veiculo
DELETE http://localhost:3000/auth/veiculos/2 HTTP/1.1
x-access-token: {{token}}

{
    "id": 2
}
### Atualizar usuario
PUT http://localhost:3000/auth/usuarios/3 HTTP/1.1
content-type: application/json  
x-access-token: {{token}}

{
    "username": "Lino",
    "senha": "Senha@123",
    "nome_completo": "Alysson Lino"
}
### Atualizar proprietario
PUT http://localhost:3000/auth/proprietarios/3 HTTP/1.1
content-type: application/json
x-access-token: {{token}}

{
    "cpf": "222",
    "nome": "Lino Atualizado", 
    "fone": "66666"
}
### Atualizar veiculo
PUT http://localhost:3000/auth/veiculos/3 HTTP/1.1
content-type: application/json
x-access-token: {{token}}

{
    "placa_veiculo": "ABC-1234",
    "id_proprietario": 1,
    "preco_veiculo": 90000.00,
    "ano": 2023
}   